<?php

namespace AppBundle\Repository;

/**
 * EventseriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventseriesRepository extends \Doctrine\ORM\EntityRepository
{
}
